--- daukle/maven: turning coordinates into the pinned blocks a toolchain takes.
---
--- This plugin resolves and pins; it compiles nothing and runs nothing. It is
--- deliberately NOT a library that daukle/java requires, because a required
--- module runs under the DEPENDENT's "uses": a java that required it would
--- have to declare the unpinned fetch itself, advertising that the Java
--- toolchain may fetch unpinned on any run. The generated file is the
--- interface instead. D-77.

daukle.plugin{ api = 1, uses = { "fetch", "cache", "pin", "write" },
               exports = { "lib/xml", "lib/pom", "lib/graph" } }

local pom = daukle.require("lib/pom")
local graph = daukle.require("lib/graph")

local OUTPUT = "classpath.lua"

--[[ Gradle resolves a conflict by taking the HIGHEST version and Maven by
     taking the NEAREST, and on the first real project measured they disagree
     about six of twenty modules. The default is Gradle's because a project
     arriving here is leaving Gradle, and "100% replace the original tool"
     is not met by a resolver that silently re-versions a third of a closure.
     It is a key rather than an inference: there is nothing left in a daukle
     project to infer the old tool from. ]]
local DEFAULT_STRATEGY = "highest"

local function config_of(context)
  return context.toolchain ~= nil and context.toolchain.config or context.config
end

local function strategy_of(config)
  local strategy = config.strategy or DEFAULT_STRATEGY
  if strategy ~= "highest" and strategy ~= "nearest" then
    error('"strategy" must be "highest", which is how Gradle resolves a version conflict, or'
          .. ' "nearest", which is how Maven does; not "' .. tostring(strategy) .. '"', 0)
  end
  return strategy
end

local function repository_of(config)
  local repository = config.repository or pom.CENTRAL
  if type(repository) ~= "string" then
    error('"repository" must be a url string, not a ' .. type(repository), 0)
  end
  return (repository:gsub("/+$", ""))
end

--- Splits "group:artifact:version" and refuses everything this resolver does
--- not model, rather than half supporting it. A range and a snapshot are both
--- moving targets, which is the one thing daukle does not have.
local function parse_coordinate(text, index)
  if type(text) ~= "string" then
    error("coordinates[" .. index .. "] must be a string, not a " .. type(text), 0)
  end
  local group, artifact, version = text:match("^([^:]+):([^:]+):([^:]+)$")
  if group == nil then
    error('coordinates[' .. index .. '] "' .. text .. '" is not "group:artifact:version"', 0)
  end
  if version:find("^[%[%(]") ~= nil then
    error('coordinates[' .. index .. '] "' .. text .. '" names a version RANGE. This resolver'
          .. ' pins, and a range is decided by whatever the registry holds at the moment it is'
          .. ' read, so two machines would not agree', 0)
  end
  if version:find("SNAPSHOT", 1, true) ~= nil then
    error('coordinates[' .. index .. '] "' .. text .. '" names a SNAPSHOT, which is republished'
          .. ' under one name and so cannot be pinned', 0)
  end
  return { group = group, artifact = artifact, version = version }
end

local function declared_of(config)
  local listed = config.coordinates
  if listed == nil then
    error('a maven toolchain needs "coordinates": there is nothing to resolve without at least'
          .. ' one "group:artifact:version"', 0)
  end
  if type(listed) ~= "table" then
    error('"coordinates" must be a list of "group:artifact:version" strings, not a '
          .. type(listed), 0)
  end
  local declared = {}
  for index = 1, #listed do
    declared[index] = parse_coordinate(listed[index], index)
  end
  if #declared == 0 then
    error('"coordinates" is empty: there is nothing to resolve', 0)
  end
  return declared
end

daukle.toolchain{
  name = "maven",
  generate = function(context)
    local config = config_of(context)
    declared_of(config)
    strategy_of(config)
    repository_of(config)
    return {}
  end,
}

local function quote(text)
  return '"' .. text:gsub("\\", "\\\\"):gsub('"', '\\"') .. '"'
end

--[[ Lua rather than TOML, and the difference is not cosmetic. A TOML fragment
     has to be PASTED into daukle.toml, which mixes generated rows into the one
     file the user writes by hand. A Lua fragment is daukle.include'd from
     daukle.lua, so the generated pins stay in a file of their own that nobody
     is ever asked to edit, and the user's manifest keeps only what the user
     wrote. It APPENDS rather than assigns, so a hand-written classpath entry
     in daukle.toml survives beside the resolved ones. ]]
local function render(entries, key)
  local lines = {
    "-- Generated by maven:resolve. Do not edit: daukle.toml is yours, this is not.",
    "-- Every url and sha256 here was fetched and hashed, because Maven Central",
    "-- publishes no .sha256 for these artifacts.",
    "--",
    "-- Include it from daukle.lua:",
    "--   daukle.include(\"daukle/maven/" .. OUTPUT .. "\")",
    "",
    "local toolchain = daukle.config.toolchains and daukle.config.toolchains." .. key,
    "if toolchain == nil then",
    "  error('daukle.config.toolchains." .. key .. " does not exist: maven resolved for \"'",
    "        .. '" .. key .. "\" but the manifest declares no such toolchain', 0)",
    "end",
    "",
    "local classpath = toolchain.classpath or {}",
    "",
  }
  for index = 1, #entries do
    local entry = entries[index]
    lines[#lines + 1] = "classpath[#classpath + 1] = {"
    lines[#lines + 1] = "  url = " .. quote(entry.url) .. ","
    lines[#lines + 1] = "  sha256 = " .. quote(entry.sha256) .. ","
    lines[#lines + 1] = "  as = " .. quote(entry.artifact .. " " .. entry.version) .. ","
    lines[#lines + 1] = "}"
  end
  lines[#lines + 1] = ""
  lines[#lines + 1] = "toolchain.classpath = classpath"
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

daukle.task{
  name = "maven:resolve",
  run = function(context)
    local config = config_of(context)
    local session = pom.session(repository_of(config))
    local resolved, rounds = graph.resolve(session, declared_of(config), strategy_of(config))

    local entries = {}
    for index = 1, #resolved do
      local module = resolved[index]
      local url = pom.url(session.repository, module.group, module.artifact, module.version,
                          "jar")
      --[[ The one unpinned fetch in the system, and the reason this task
           needs --resolve. What comes back is the digest core computed while
           writing the file, which is exactly the pin daukle.artifact wants. ]]
      local pinned = daukle.pin{ url = url, as = module.artifact .. " " .. module.version }
      entries[index] = {
        artifact = module.artifact, version = module.version,
        url = url, sha256 = pinned.sha256,
      }
    end

    local into = config["for"] or "java"
    --[[ committed, because a clone has to build without resolving again: an
         ordinary build may not fetch anything unpinned, so the pins have to be
         in the project's history. It lands in daukle/maven/ rather than
         build/daukle/maven/, which daukle clean deletes. ]]
    local path = daukle.write{ path = OUTPUT, text = render(entries, into), committed = true }
    --[[ A plugin has no way to print, so the file IS the report. Raising here
         would fail the task, so the count reaches the user through the
         acquisition report daukle.pin already writes: one line per artifact,
         each naming its url and the digest this run computed. ]]
    return path
  end,
}

--- Resolution alone, with no fetching and no digests, so the closure can be
--- compared against what the old tool produced before anything is downloaded.
--- 21.5 MB separates this task from maven:resolve on the project measured.
daukle.task{
  name = "maven:list",
  run = function(context)
    local config = config_of(context)
    local session = pom.session(repository_of(config))
    local resolved, rounds = graph.resolve(session, declared_of(config), strategy_of(config))

    local lines = {
      "# " .. #resolved .. " modules, " .. rounds .. " rounds, " .. session.fetches
      .. " POM fetches",
      "",
    }
    for index = 1, #resolved do
      local module = resolved[index]
      lines[#lines + 1] = module.group .. ":" .. module.artifact .. ":" .. module.version
    end
    if #session.unversioned > 0 then
      lines[#lines + 1] = ""
      lines[#lines + 1] = "# dependencies reached with no version, and therefore skipped:"
      for index = 1, #session.unversioned do
        lines[#lines + 1] = "#   " .. session.unversioned[index]
      end
    end
    return daukle.write{ path = "resolved.txt", text = table.concat(lines, "\n") .. "\n" }
  end,
}
