-- Generated by maven:resolve. Do not edit: daukle.toml is yours, this is not.
-- Every url and sha256 here was fetched and hashed, because Maven Central
-- publishes no .sha256 for these artifacts.
--
-- Include it from daukle.lua:
--   daukle.include("daukle/maven/classpath.lua")

do
  local toolchain = daukle.config.toolchains and daukle.config.toolchains.demo
  if toolchain == nil then
    error('daukle.config.toolchains.demo does not exist: maven resolved for "'
          .. 'demo" but the manifest declares no such toolchain', 0)
  end

  local classpath = toolchain.classpath or {}

  classpath[#classpath + 1] = {
    url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar",
    sha256 = "d3ef575e3e4979678dc01bf1dcce51021493b4d11fb7f1be8ad982877c16a1c0",
    as = "slf4j-api 1.7.36",
  }

  toolchain.classpath = classpath
end

do
  local toolchain = daukle.config.toolchains and daukle.config.toolchains.other
  if toolchain == nil then
    error('daukle.config.toolchains.other does not exist: maven resolved for "'
          .. 'other" but the manifest declares no such toolchain', 0)
  end

  local classpath = toolchain.classpath or {}

  classpath[#classpath + 1] = {
    url = "https://repo1.maven.org/maven2/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar",
    sha256 = "48e2df636cab6563ced64dcdff8abb2355627cb236ef0bf37598682ddf742f1b",
    as = "opentest4j 1.3.0",
  }

  toolchain.classpath = classpath
end
